name: Dummy Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo "Hello, world!"

      - name: azure login
        run: az login --service-principal --username 745b543b-e354-4b35-9cf3-97e8de1592a3 --password 99x8Q~GhWNAXa0LWWVwcSKrVRgT0PcMlQArTEaEm --tenant cca441fa-1a33-47c9-99a1-76ffc55ce3bf
          
      - name: terraform init
        run: terraform init
      - name: plan
        run: terraform plan

      - name: apply
        run: terraform apply -auto-approve
